# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: aps-users-db
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./.docker/init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"